pipeline {
	agent any
		stages {
			stage('Clean stage') {
				steps {
					dir("StockPricesApp") {
						bat 'C:\\apache-maven-3.6.3\\bin\\mvn clean'
					}
				}
			}
			stage('Compile stage') {
				steps {
					dir("StockPricesApp") {
						bat 'C:\\apache-maven-3.6.3\\bin\\mvn compile'
					}
				}
			}
			stage('Install stage') {
				steps {
					dir("StockPricesApp") {
						bat 'C:\\apache-maven-3.6.3\\bin\\mvn install'
					}
				}
			}
			
		}
}


